webview/webview

README.md
webview.go
webview.h

* Adds `webview_debug()` to print logs to stderr on Linux, Console app on MacOS and DebugView on Windows. It enables logging when there is no terminal available.
* Adds `webview.Debug()` and `webview.Debugf()` in Go
* Adds `debug` and `webview.Settings.Debug` field to enable WebInspector on Linux and MacOS.
All the above, plus FirebugLite on Windows make it a pleasant environment for building web UI.

Webview debug

---

webview.h

I apologize. Actually it has not worked at all that ensuring the return value of `evaluateWebScript` is the class `WebUndefined`. That have been always `YES`. I guess that we can not determine whether if an exception is thrown or not explicitly in WebScriptObject.

cocoa: rollback eval to not returning -1

---

webview.go

This causes an error on windows because -mwindows is not a proper flag

Make it actually work on windows

---

webview.h

Visual Studio doesn't set STARTF_USESHOWWINDOW flag in the STARTUPINFO when running an app and set wShowWindow to zero, so using it for ShowWindow effectively hides the window.
One can use SW_SHOWDEFAULT flag which use STARTUPINFO field if correspondning flag is set.

Fix showing window on Windows under debugger

---

webview.h

The `webview_dispatch_arg *context` in `webview_dispatch` is only being allocated the size of a pointer to the context, not the size of the struct itself. This results in invalid memory access on the subsequent lines.

Fix under allocation of webview_dispatch_arg

---

README.md

The link to go-bindata was to an outdated, unmaintained repository.
This PR simply updates it to a maintained version.

updates go bindata link to a maintaned repo

---

webview.h

**This PR is a proposal.**  
I am not the owner of this project and my words should not be considered as such.
This PR makes WKWebView able to display Open and Save panels as well as JS alert and confirmation boxes. Proper download functionality has also been implemented.
**Rationale:**
I noticed the Linux/Windows versions of webview natively handle this functionality so the Mac/Cocoa version _should_ be able to as well.  I can definitely imagine a scenario where someone wrote a Javascript SPA that relies on this functionality would expect it to work the same on **all** platforms.  There are many use-cases where someone would not need/use JS <-> Native communication but still need to upload/download files, ask for confirmation, and alert the user of an error.   If this JS developer …

Standardizing JS behavior for Cocoa

---

webview.h

I am pretty sure that `wchar_t*` is enough.

minor L"eval" in Windows

---

webview.h

Fixes uninitialized FILEOPENDIALOGOPTIONS variable used to display
dialogs on Windows.
This sometimes caused problem in debug builds vs release builds.
Sometimes the dialog would not show and sometimes it would (There was
probably some garbage initialized to these variables in debug builds
and they were correctly initialized to 0 in release builds).
This also fixes Boscop/web-view#29.

Fix uninitialized variable

---

webview.h

In WebkitGTK 2.22 webkit_javascript_result_get_value() was depricated in
favor of webkit_javascript_result_get_js_value().  This change will use
the new JSC API when WebkitGTK 2.22 is present.
Fixes #192

Move to JavaScriptCore Glib API over DOM API

---

webview.h

Hello,
This fixes the `s/setTitle/setTitle:/` selector typo.
This causes webview to crash, with the following error, when changing the title on macOS.
`unrecognized selector sent to instance`
Tested on macOS Sierra version 10.12.6.
`setTitle:` is used [elsewhere](https://github.com/zserge/webview/blob/e94d679fff454c6e4f660e12ff92d17a508014eb/webview.h#L1876) in the code base.
:+1:

Fixes set title selector typo for macOS.

---

webview.h

Both, [GetMessage ](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getmessage) and [PeekMessage](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-peekmessagew), can end up not filling out the msg struct.
In those cases we have garbage in the struct and must not handle anything.
#220 Fix

Do NOT handle uninitialized messages

---

webview.go

This fixes #323.
For some reason (I don't know why), the binding is deleted after it is invoked. So it works on the first time (and then it is deleted) and then fails on the second time. In `_webviewBindingGoCallback`, `f` becomes nil.
Also, just wondering, is it actually necessary to mutex-lock `bindings`? After this PR, `bindings` is modified by `Bind` but it is read-only by `_webviewBindingGoCallback`. Since there is only one writer, maybe the mutex is unecessary?

(Go) Don't delete binding after it is called.

---

webview.h

In some occasions, if compiled in Release Mode, the variables m_minsz and m_maxsz were pointing to random memory. This caused weird effects on windows. From application crash to operating system crash.

Initialize point vars for windows

---

webview.h

[Infer](https://github.com/facebook/infer) reports that there is a potential null pointer dereference:
```
webview.h:597: error: NULL_DEREFERENCE
pointer `w` last assigned on line 594 could be null and is dereferenced at line 597, column 23.
595.                             (cocoa_wkwebview_engine *)objc_getAssociatedObject(
596.                                 self, "webview");
597. >                       w->on_message((const char *)objc_msgSend(
598.                             objc_msgSend(msg, "body"_sel), "UTF8String"_sel));
599.                       }),
```
According to the declaration of `objc_getAssociatedObject`, it can potentially return `null`:
```
OBJC_EXPORT id _Nullable
objc_getAssociatedObject(id _Nonnull object, const void * _Nonnull key)
OBJC_AVAILABLE(10.6, 3.1, 9.0, …
```

Fix potential null pointer dereference on macOS

---

README.md

Needed to add the std=c++11 switch when compiling for macos.

Add -std=c++11 switch to macos command line

---

webview.h

This PR adds the executable icon to the titlebar of the webview window. It pulls the resource icon directly from the executable.
Enhanced PR of #358

Add titlebar icon for windows

---

webview.h

This PR simplifies `set_size`. Creating a struct called `size` and setting `width` and `height` properties seems a bit unnecessary when the `CGSizeMake` API does the same thing:

Simplify set_size on macOS

---

script/build.bat

The Windows build is currently passing, but it should be failing because there's a [compiler error](https://github.com/webview/webview/runs/790981798#step:3:21)

fix(workflows): Fail the build if there is a compiler error

---

.github/workflows/ci.yaml

It seems like the build/test workflow does not run on PRs. If we enable it on PRs, contributors (and maintainers) can be confident that everything builds properly before something is merged to `master`﻿

Run CI pipeline on PRs

---

webview.h
webview_test.cc

Add the required header and avoid ambiguous symbol to make windows workflow works again. There's an assert test removed from this PR too, because ms c/cpp compiler seems have different opinion on raw string literals than linux/mac. Besides, it's not a valid JSON either.

Fix windows CI

---

README.md

This commit changes the link to point to the "official" c# bindings

Change C# Bindings Link

---

.github/workflows/ci.yaml
webview.h

To enforce the code style, `clang-format` should be run on PRs

Run clang-format as part of CI pipeline

---

README.md

Previously webview_destroy was not called in either the C++ example or the C example. Now it is called in both, following the documentation in webview.h

Add webview_destroy to README examples

---

webview.h

This PR enables JavaScript clipboard access for Linux, MacOS & Edge Chromium on Windows.
For Linux & macOS it enables both `document.execCommand("paste)` & `navigator.clipboard`, however for Edge Chromium only the latter.
I have not been able to find any info about enabling clipboard access for EdgeHTML so I assume it only works with a custom implementation. Since the Webview Runtime is dropping Q3 and will make the EdgeHTML integration obsolete it doesn't seem worth the effort though.

Allow JS to access clipboard

---

README.md

The build command previously had different names for the C/C++ examples as the example file had. This corrects the error.

Make C/C++ example filenames consistent

---

README.md

There is a small typo in README.md.
Should read `transparency` rather than `trancparency`.

docs: fix simple typo, trancparency -> transparency

---

README.md

Introduced with 7d93e90a9565a016f5ef65ca810f97a99bf6b44c, README mentions a call to the `destroy()` in the C++ example.
This method does not exist:
```c++
error: ‘class webview::webview’ has no member named ‘destroy’
36 |     w.destroy();
|       ^~~~~~~
```

Fix README mention of non-existing C++ destroy() method

---

webview.h

The use of `objc_msgSend` with `OBJC_OLD_DISPATCH_PROTOTYPES` is dangerous. The new prototypes were introduced specifically to prevent odd behavior that may occur as a result of how variadic parameters are handled (see [this article](https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html)). This PR updates each call to `objc_msgSend` so that it is casted appropriately for the corresponding Objective-C call.

fix: Use new prototypes for objc_msgSend

---

README.md

This documents [@petabyt's approach](https://github.com/petabyt/webviewc) for compiling webview with a C++ compiler and the C program with a C compiler, then linking them together. This requires setting WEBVIEW_HEADER in C to tell gcc to only use the header and ignore the rest of webview.h, which is in C++, so gcc can't compile it.
The explanation is much longer than before, because there are now more steps. To simplify it, we first set an environment variable for platform-specific C++ flags and keep the build process the same for Linux, macOS, and Linux.
This approach is better than using a C++ compiler to compile C++, since C and C++ have some discrepancies. It also has the added bonus of faster incremental and initial compilation.
The results are identical as before, with a …

Use C compiler for C example in README

---

webview.go

This adds NetBSD to the list of compatible targets for the Go bindings. It uses webkit-gtk like Linux, OpenBSD, and FreeBSD already do.
This allows using `go get` directly on NetBSD without having to modify the bindings.
Resolves #548

Add NetBSD compatibility to Go bindings

---

webview.h

Resolved RPC promises were undefined. Now, they are completely deleted.
Before:
`window._rpc == { 1: undefined, 2: undefined, 3: <pending>, nextSeq: 4 }`
After:
`window._rpc == { 3: <pending>, nextSeq: 4 }`

Resolved rpc promises should not stay in the window._rpc array.

---

webview.h

* do not initialize/uninitialize COM, it is not our task
* do not use deprecated codecvt C++ methods, use WinAPI methods instead
* string conversion using winrt::to_string and winrt::to_hstring helpers
* do not read APPDATA environment variable, use WinAPI method instead
* always use Unicode API methods, this will allow to compile regardless "Character set" application option

Windows fixes

---

webview.h

Line 1251 fixes a preexisting memory leak. That line dynamically allocates a pointer which we **never** use. Since it is passed as a `void*`, we cannot free that memory. Deleting a void pointer is undefined behavior.
The rest of the code is based on https://github.com/CptWesley/webview/commit/9e8794dc67f56d6c7dc060e85d10b77a98e626c3, though I needed to fix some memory leaks.
This library provides a way to bind JS and C functions, but it does not allow the user to unbind. As noted in issue https://github.com/webview/webview/issues/644, that is a security issue, so I believe this PR should be merged.

Create unbind function

---

script/build.bat

/b parameter keeps the parent window open, allowing the error message to be seen in cmd.

build.bat: Use /b parameter on errors

---

webview.h

Remember this PR? https://github.com/webview/webview/pull/663 I stupidly said line 1244 "is not used." Actually, it is 🤦‍♂️. So this time I fix the memory leak by deleting the pointer properly. A second set of eyes on this would be awesome!

Fix stupid mistake I made earlier

---

webview.h

Fixes part of #643 by encoding HTML data URIs before converting and then passing onto the webview. Previously, it would encode it *after* it was applicable.

Don't decode HTML when passed as data URI

---

README.md

As more bindings are listed in the README, writing "X bindings" for each is quickly becoming unwieldy. This rewords it to make it more readable.

Simplify wording for bindings in README.md

---

README.md

Fixes #649 and #694.
For now, I am just dumping this into the `README.md`. In the future, this should probably live in the `docs` repository.
Signed-off-by: Nicklas Frahm <nicklas.frahm@gmail.com>

Document known issues

---

webview.h

This will resolve #678.
I think we need to merge https://github.com/webview/webview/pull/684 and https://github.com/webview/webview/pull/666 first. Otherwise, EdgeHTML support seems up-to-date to me. If we decide to, this PR will reduce the scope of our library and will leave users who want to support EdgeHTML with a working API (after merging what I suggest above).
Note: after we merge this, any open PR that affects windows will have to update their PR. We should double-check their status first.

Remove EdgeHTML

---

main.c
script/build.sh

This adds the C example found at webview/webview_c to the main repository, and configures the Unix build scripts to test it in CI. This will ensure that the C example is constantly tested as well as the C++ one.
It currently does not add the C example to the Windows tests. That can either be added to this PR or separately if desired.

Add C example to main repo

---

webview.h

Resolves #698.
Navigate and set_html work with edgehtml again. `NavigateToString` expects a raw html string.
Added the set_html capability back to `navigate` if the user passes a "data:text/html," uri in.

Add backwards compatability to navigate and fix set_html

---

webview.h

Previously, compiling on various BSDs required setting WEBVIEW_GTK
directly. This automatically defines WEBVIEW_GTK Unix platforms
(after checking for Apple, in case macOS defines `__unix__`).
The Go bindings already do this for various Unix systems.
Resolves #431

Define WEBVIEW_GTK on other Unix platforms

---

webview.h

I suggest this change to avoid compiling the word "Hello" into the executable consuming the library and because it is an unwanted side effect.
While I find it questionable that an empty URL should be permitted, I do not have strong opinions about it.
Preferably I would like to avoid embedding the string `<html><body></body></html>`.

Do not display "Hello" when URL is empty

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Add link to our API docs online.
Removed known issues that apply only to EdgeHTML.
Removed Migration guides.
Changed Windows build instructions to use build script.
Added Windows info to the Notes section.
Added a contributing section and some guidelines we discussed for examples.

Update README with more information.

---

webview.h

Close https://github.com/webview/webview/issues/726
This change makes sure that after `.navigate()` is called the webview has the user focus as it should.

Win32: Fix focus after navigation

---

main.cc
webview.h
webview_test.cc

I would like to propose changing parameters of type `std::string` to `const std::string&` because it is generally a good practice.

Use reference to const string

---

webview.h

Fixes the following warning (GCC) in C++20 mode:
```
implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
dispatch([=]() {
```
`[=, this]` only became available since C++20:
```
explicit by-copy capture of ‘this’ with by-copy capture default only available with ‘-std=c++20’ or ‘-std=gnu++20’ [-Werror=c++20-extensions]
dispatch([=, this]() {
```
This PR explicitly captures everything and eliminates the original warning.
Is there any other way to do this?

Fix implicitly capturing "this" in lambda function

---

webview.h

This PR removes code related to hex/URL decoding, and is an attempt to resolve concerns raised in the following PR that instead optimizes hex decoding:
* https://github.com/webview/webview/pull/739

Remove unused hex/URL decode code

---

script/build.bat

Enabling warnings for MSVC reveals a new warning inside `json_parse_c`:
```
webview.h(177): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
```
`json_parse_c` has a dual purpose and it's hard to understand the code at first glance and not easy to correctly change just the offending code. This is something that should be dealt with another time.
Warning `C4100` (unreferenced formal parameter) was disabled to be consistent with the other compilers.

Enable warnings for MSVC

---

webview.h
webview_test.cc

This work replaces the `url_encode` function with a dumber `percent_encode` function that is optimized for code execution:
* Characters are always percent-encoded which eliminates branch/comparison instructions inside the loop over the input string.
* All memory for the resulting string is allocated upfront since the amount required can be calculated trivially.
* Encoding is trivial enough to not need snprintf.
The runtime efficiency improvement over the existing code is quite significant for long strings at the cost of more memory reserved for the resulting string.
On my machine the new code performs about 148 times better with a small (16.4 KB) but real-world minified HTML document with embedded styles and scripts.
Here is a comparison of the generated code: …

Optimize URL/percent encoding

---

webview_test.cc

I am not sure what kind of quality we are aiming for regarding the current JSON implementation but eventually I think it would be nice to tidy up a bit. I added some more tests to get a better idea of what to expect from the current implementation.

Add more JSON parsing tests

---

script/build.bat
webview_test.cc

This PR enables tests in the build script for Windows which allows the tests to run as part of the CI process.
This required increasing the test timeout from the current 5 seconds because the time between calling `CreateCoreWebView2EnvironmentWithOptions` and invocation of `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` can be more than 5 seconds when running on GitHub Actions. I have seen it take just over 25 seconds.
I would like to know why it takes so long but I have not yet been able to figure it out. I am unable to reproduce it locally. Maybe it is simply due to lack of resources on GitHub Actions but it would be nice to confirm it.
In any case I think that slow tests are better than no tests.

Enable tests on Windows

---

webview.h
webview_test.cc

Eliminates the need for percent-encoding and has therefore been removed.

Call NavigateToString instead of Navigate

---

script/build.bat
webview.h
webview_test.cc

Adds support for Windows 7 through 8.1 changing the following:
* Use available DPI awareness API instead of API that is only available since Windows 10.
* Remove usage of WinRT and umbrella library only available since Windows 10.
This PR closes #752.
The screenshots below show one of the example apps included with this library running on Windows 7, 8 and 10 with 100% scaling and 150% scaling.
The app looks nearly identical to how it looks on Windows 10.

Support old Windows

---

webview.h

Fixes the main window not having a shadow by specifying `NSWindowStyleMaskTitled` when creating the window.
Setting the style only in `set_size` is not enough, and removing it from `set_size` also removes the title bar which is undesired.
Conclusion: Specify `NSWindowStyleMaskTitled` both when creating the window and when setting the style mask in `set_size` so that the shadow is enabled correctly for the window.
This PR closes #674.

Fix window shadow on macOS

---

webview.h

Reference counting is now implemented for webview2_com_handler so that
it can be released properly. The cloned pointers to ICoreWebView2Controller
and ICoreWebView2 are now being released and it is more clear when the
pointers are cloned.
These actions fix an issue where WebView2 initialization can hang for a
variable amount of time and cause tests to time out.
With the old code on my local environment, tests that use WebView2
oftentimes hang for about a minute. We have also seen how the CI job
tends to hang, likely for the same reason.
I do not think that it has anything to do with the tests themselves but
rather the right sequence of events paired with leaks in a short period
of time.
The hang happens after a successful call to
ICoreWebView2Environment::CreateCoreWebView2Controller
and …

Fix resource leaks causing hang on Windows

---

README.md
main.c
webview.go
webview.h

C++ code will not work anyway when compiling a C program so we can remove the requirement for library users to define `WEBVIEW_HEADER` when compiling C code.
C++ code is still in a `#ifndef WEBVIEW_HEADER` guard to avoid breaking compatibility with existing C++ code that defines `WEBVIEW_HEADER`.

Exclude all C++ code when compiling in C mode

---

webview.h

This should make it easier for MinGW. Fixes #768.
I'll do a round of testing in a few hours.

Redefine modern win32 types for DPI

---

.gitignore

Ignores e.g. `nuget.exe` on Windows. I consider this a temporary fix until we tidy up.

Add exe to gitignore

---

.github/workflows/ci.yaml
README.md
script/build.bat
webview.go

The Windows CI build has been broken since #773 and it has not been detected because the build has been reported as successful despite the build script exiting with a non-zero exit code.
Builds have worked in my local environment with Go 1.18 which has a fix for an issue with quotes/spaces in environment variables (e.g. `CGO_LDFLAGS`), while GitHub Actions has Go 1.17.11 currently without the [fix for that issue](https://go-review.googlesource.com/c/go/+/334732/).
I have fixed a few other things as well in the build script for Windows.

Fix Windows CI build

---

webview.h

The [reference counting rules](https://docs.microsoft.com/en-us/windows/win32/learnwin32/managing-the-lifetime-of-an-object#reference-counting) of COM objects state that new objects have a reference count of 1.

Fix COM handler reference counting

---

webview.h

The COM handler class returned `S_OK` from `QueryInterface` without assigning anything to the return parameter.
The documentation for `IUnknown::QueryInterface` states the following:
* On success, `*ppvObject` contains a pointer to the requested interface.
* If the interface is unsupported, `*ppvObject` is set to `nullptr`.
* Returns `S_OK` if the interface is supported; otherwise `E_NOINTERFACE`.
* Returns `E_POINTER` if `ppvObject` is `nullptr`.
Since we do not return any valid pointer then we might as well return `E_NOINTERFACE`.

Fix QueryInterface implementation

---

webview.h

Fixes multiple definition errors for these functions.

Make some Windows-only functions inline

---

examples/basic.c
examples/basic.cc
examples/bind.c
examples/bind.cc

With MSVC, `_WIN32` is always defined while `WIN32` is only defined after including the `Windows.h` header. Since the C examples did not include the Windows header then `WIN32` was not defined and therefore the executable did not use the proper `WinMain` entry point.

Check _WIN32 instead of WIN32

---

webview.h

Splits some code into functions to improve readability and to avoid duplicate code.
* App delegate creation has been moved into `create_app_delegate()`.
* Retrieval of the shared `NSApplication` instance has been moved into `get_shared_application()`.
* Retrieval of the associated `cocoa_wkwebview_engine` instance from the app delegate has been moved into `get_associated_webview()`.

Refactoring for macOS

---

webview.h

Miss me?
Finally got some time to work on resolving #728.
To test this, add the line `webview_unbind(w, "increment");` in examples/bind.c. Then, compile it. You'll notice it segfaults and crashes as @silversquirl reported.
Now, checkout the changes I made and do the same thing. Make sure to recompile `webview.o`. You'll notice that the app runs as it should, and when clicking the button, nothing happens - score!
I had a previous PR that fixed a memory leak with the sync bindings, but it caused this segfault since the async bindings allow users to supply whatever they want as the `arg` param. Oops. Of course, if the user dynamically allocates a variable and passes it into the async `bind`, they are responsible for cleaning that up upon `unbind`. We don't expect the user to deallocate our …

Webview unbind

---

webview.h

This fixes an issue on Windows where webview construction would cause the program to crash when the WebView2 runtime was not installed. `webview_create` now returns null this case.
`CreateCoreWebView2EnvironmentWithOptions` would return `HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND)` (`0x80070002`); the value returned by `embed()` (`false`) would not be checked in the constructor of `win32_edge_engine`; it would then crash when attempting to call `MoveFocus()` via `m_controller` which was `nullptr`.
This fix does not add a check for `embed()` but instead checks much earlier if the WebView2 runtime is available, avoiding creating the window just to destroy it again.
We should still check the return value of `embed()` but this simple fix requires less testing and can therefore be merged sooner. …

Fix crash when WebView2 runtime not installed

---

README.md

The bundles themselves are just directories, not zip archives.

Fix macOS app bundle info

---

webview.h

Notable changes:
* Set the activation policy only if the app is not bundled.
* Activate the app only if the app is not bundled.
* Whether the app is bundled is determined by checking whether the bundle path has the `.app` suffix.
* Note: Launching the executable directly within the bundle will cause `is_app_bundled()` to return `true` and therefore the app will not attempt to activate itself, but I do not really see it as a problem.
* `run()` no longer calls `dispatch` in order to invoke of `activateIgnoringOtherApps:` after the main run loop has started. Instead `applicationDidFinishLaunching:` is handled and the app is activated there.
* The constructor of `cocoa_wkwebview_engine` no longer creates the window. It is now done in `applicationDidFinishLaunching:`.
* The constructor of …

Reorder macOS app initialization

---

webview.h

Adds a C++ variadic template to allow calling `objc_msgSend` easily with argument type deduction.
Instead of redefining constants used internally using `#define`, `enum`s are used with the correct underlying types such as `NSInteger` whose size varies depending on the target CPU architecture. Also avoids preprocessor definition pollution for those constants.
Use Objective-C-style `YES`/`NO` instead of `1`/`0`.

Simplify Objective-C runtime calls

---

webview.h

Tapping the button of an HTML file input field has out of the box displayed a dialog for selecting files on Linux and Windows, but this was not the case on macOS as failing to implement the necessary method of [`WKUIDelegate`](https://developer.apple.com/documentation/webkit/wkuidelegate?language=objc) would result in the operation being canceled with no dialog being displayed.
This PR adds an implementation of [`webView:runOpenPanelWithParameters:initiatedByFrame:completionHandler:`](https://developer.apple.com/documentation/webkit/wkuidelegate/1641952-webview?language=objc) that displays a file upload panel and passes the file paths/URLs back to the web view.
I have tested this with the following C++ example:
```cpp
#include "webview.h"
#ifdef _WIN32
int WINAPI WinMain(HINSTANCE hInt, …
```

Implement file input for macOS

---

webview.h

Splits the `webview2_com_handler` class from the `win32_edge_engine` class, making code navigation easier. Both classes are in the `detail` namespace so this is fine.

Split webview2_com_handler from win32_edge_engine

---

webview.h

When compiling the library on Windows in C++14 mode using clang 14 from WinLibs' version of MinGW-w64, existing code would fail to compile due to `atomic(const atomic&)` being explicitly deleted.
The error is in the `atomic` header from Visual Studio 2022.
Using the normal constructor instead fixes the problem.

Avoid copy-constructor of std::atomic

---

webview.go

This lets Go-developers utilize the recent fix in [PR 807](https://github.com/webview/webview/pull/807). webview.New will return nil when users don't have WebView2 Runtime installed. Currently when users lack the Runtime, it returns an interface with no way (at least that I was able to figure out) to check if initialization was a success, and calling Window() on it causes a crash.

Returns nil in Go/NewWindow when C.webview_create returns NULL

---

webview.h

On macOS, initializing the library with an existing window likely means that the user wants to be responsible for setting up the application, and likely means that the user intends to manage the application lifecycle. If the library waits for the "applicationDidFinishLaunching:" message in this case then it may never receive the it.
Since the library still replaces any existing app delegate with its own, this change is consistent with behavior that existed in the library before it began expecting the "applicationDidFinishLaunching:" message.

Expect applicationDidFinishLaunching only when window was not passed

---

webview.h
webview_test.cc

I am submitting this PR with #707 in mind. The initial work was ripped out of #766 but I decided to rewrite it.
Feedback would be most welcome so that we do this properly the first time.
Which version would you prefer to set in this PR? It is currently set to 0.11.0 but 0.10.0 could also be a candidate.
Would you prefer a default value for `WEBVIEW_VERSION_PRE_RELEASE`?
Closes #442.
Program:
```cpp
// These preprocessor definitions are merely for demonstration purposes.
#define WEBVIEW_VERSION_MAJOR 1
#define WEBVIEW_VERSION_MINOR 2
#define WEBVIEW_VERSION_PATCH 3
#define WEBVIEW_VERSION_PRE_RELEASE "-dev"
#define WEBVIEW_VERSION_BUILD_METADATA "+gdd38be8"
#include "webview.h"
#include <iostream>
int main() {
auto vi = webview_version();
std::cout << "major: " << vi->major << "\n"
<< …
```

Add library version

---

script/build.bat

The main issue fixed is an error that occurs when attempting to run the Windows build script (`build.bat`) when the working directory is not the root directory of the repository.
The other issue is just an aesthetic one where double quotes no longer appear around some printed messages.

Fixes for Windows build script

---

README.md
script/build.bat
webview.go
webview.h

According to #888, LLVM-based MinGW-w64 has a problem with linking `WebView2Loader.dll.lib` when the `-static` flag is used, which is the case when using the Go bindings.
This PR takes some bits from #783 in order to allow linking `WebView2Loader.dll` explicitly so that one can eliminate the need for the `WebView2Loader.dll.lib` file.
Note that when linking `WebView2Loader.dll` explicitly and the file isn't present then the user will no longer be presented with a message box stating that the DLL was not found. Instead of recreating such a message box, I would prefer to return an error code from the library (#766). The new behavior is acceptable to me because the readme explicitly states that one should bundle the DLL.
For now this is an opt-in feature of the core library that can be …

Allow linking WebView2Loader.dll explicitly

---

webview.h

Fixes some of the multiple definition errors when `webview.h` is included in multiple C++ source files.

Make some internal functions inline

---

.github/workflows/ci.yaml
README.md

Changes:
* Rewrote the SWIG section the readme.
* Output to `build/bindings` directory.
* Added CI configuration for SWIG based on examples in readme.
* Added `-Wall -Werror` flags to `swig` command in CI config.

SWIG info and CI config

---

examples/bind.c
examples/bind.cc
examples/bind.go

Add asynchronous binding example for C and C++.
No example was added for Go because I couldn't immediately see that the
current Go bindings allow for it.

Async binding example for C/C++

---

webview.h

Use `NSAutoreleasePool` as suggested by @jakenvac to release memory allocated during `navigate`/`set_html`, with a wrapper class that drains the pool on destruction.
Fixes #882.

Use autorelease pool on macOS

---

webview.h

This PR replaces the following PR:
* #940
This combined work makes `WKWebView` inspectable via Safari on OS versions that disable the feature by default (macOS 13.3 and later) and support enabling it.
According to Apple, the behavior on older OS versions is for content to always be inspectable in "debug builds".
Testing shows that this is true for macOS 12.6 but not macOS 10.15.
A runtime check avoids crashing the program on OS versions that do not support the `setInspectable:` selector.
macOS | Safari | `setInspectable:`
| - | - | - |
10.15.7 | 15.6.1 | no
12.6.6 | 16.5 | no
13.4.1 | 16.5.1 | yes
macOS | Safari | default | w/devtools | w/inspectable
| - | - | - | - | - |
10.15.7 | 15.6.1 | no | no | n/a
12.6.6 | 16.5 | yes | yes | n/a
13.4.1 | 16.5.1 | no | no | yes

Make WKWebView inspectable via Safari

---

.github/workflows/ci.yaml
examples/basic.c
examples/bind.c
script/build.sh
webview.h
webview_mingw_support.h

This is an attempt at a minimalistic rewrite of the build.sh script that aims to improve compatibility with MinGW-w64 and cross-compilation from Linux to Windows (C,  C++ and Go), with some quality of life improvements. It isn't meant to be a permanent solution but rather something that takes some pain away while developing and testing the library.
Code has been split into smaller tasks that can be run individually by specifying them on the command line. Specifying no tasks runs the default set of tasks, while specifying one or more tasks runs only those tasks.
Example usage: `build.sh clean deps build test`
The default C and C++ compiler executables remain the same (cc/c++) but can now be overridden using the `CC` and `CXX` environment variables.
Example of cross-compilation from Linux …

Rewrite build.sh script

---

script/build.sh

Fixes issue with the script failing when the working directory isn't the same as the project directory.

Use absolute paths when creating build directories

---

script/build.sh

Builds the library as a shared library on each platform:
* `*.so` on Linux.
* `*.dylib` on macOS.
* `*.dll` on Windows.
Doesn't build examples with shared linking of the library but I'll provide examples for that below.
```
mkdir -p dist
./script/build.sh clean build
cp build/library/libwebview.so dist/
cc -c examples/basic.c -std=c99 -I. -o build/basic.o
c++ build/basic.o '-Wl,-rpath,$ORIGIN' -Lbuild/library -lwebview -o dist/basic
./dist/basic
```
```
mkdir -p dist
./script/build.sh clean build
cp build/library/libwebview.dylib dist/
cc -c examples/basic.c -std=c99 -I. -o build/basic.o
c++ build/basic.o -rpath @executable_path -Lbuild/library -lwebview -framework WebKit -o dist/basic
./dist/basic
```
```
mkdir -p dist
./script/build.sh clean deps build
cp build/library/libwebview.dll …
```

Build shared library in build.sh

---

.github/workflows/ci.yaml
script/build.bat

Similarly to PR # #957 for `build.sh`, this PR overhauls `build.bat`.
`build.bat` is still MSVC-specific but retains support for Go. Linting isn't implemented here both because it wasn't originally implemented, and because it would have needed different compiler and linker flags for `clang-tidy`.
The only cross-compilation support implemented is for MSVC by setting the `TARGET_ARCH` environment variable to `x86` or `x64`
The script no longer builds the library for both `x86` and `x64` in a single invocation—instead it should be controlled with `TARGET_ARCH`.
`CC` and `CXX` can be set for Go but isn't used for C/C++ unlike `build.sh`—instead `cl` is always used for C/C++.
Example:
```bat
set TARGET_ARCH=x86
set CC=i686-w64-mingw32-gcc
set CXX=i686-w64-mingw32-g++
script\build.bat
```
The …

Rewrite build.bat script

---

README.md
script/build.bat
script/build.sh

Allows overriding the path of the build directory using the `BUILD_DIR` environment variable in order to produce build artifacts in an alternative location.
Useful for out-of-source builds or multiple configurations with separate build directories

Allow build directory override

---

webview.h

This suggestion includes some small updates to the API comments.
* It mainly makes uniform usage of prepositions. Using `a` and `the` is already was the dominant style in the comments. The changes make it consistent.
* Includes small fixes
```diff
- // the webview will open a the new page - this initialization code will be
+ // the webview will open the new page - this initialization code will be
- // must be provided to help internal RPC engine match requests with responses.
+ // must be provided to allow the internal RPC engine to match requests and responses.
```
* Extends commenting to include `*seq` (request id) for requests
```diff
- Callback receives a request string and a user-provided argument pointer.
+ The callback receives a sequential request id, a request string and a …
```

Update API comments

---

.github/workflows/ci.yaml
script/build.bat
script/build.sh
webview.go
webview.h

This should be a backward-compatible change because the library is statically linked into Go programs and the library's own dependencies such as the C++ runtime library are also statically linked using the `-static` flag.

Lower C++ standard requirement from C++17 to C++14 on Windows

---

webview.h

Stops the run loop after the last window is closed instead of terminating the app; otherwise user code would have no way of cleaning up.
Closes #989
Closes #372

Stop run loop instead of terminating app on macOS

---

webview.h

Scales when the DPI setting changes on the window's display:
[change_dpi.webm](https://github.com/webview/webview/assets/1543854/adfe2186-9534-4548-898c-bd49d72ed233)
Scales when moving window to display with different DPI:
[move_between_displays.webm](https://github.com/webview/webview/assets/1543854/621544ad-b3c7-4a52-83c2-b1637d3bf30f)
| Case | Description                                                    | Expected                        |
| ---- | -------------------------------------------------------------- | ------------------------------- |
| 1    | Start on primary display with 100% DPI.                        | Window not scaled.              |
| 2    | Start on display with >100% DPI when primary display at 100%.  | Window scaled up.               |
| 3    | Start on primary …

DPI scaling for Windows 10 and later

---

webview.h

Replaces `is_os_version_at_least()` with `compare_os_version()` to allow for more flexible comparisons.

Refactor OS version comparison

---

webview.h

1. Start app with light theme enabled for apps (system-wide setting). The titlebar color should be light.
2. Change the theme to dark and observe that the titlebar color changes to dark.
3. Start app with dark theme enabled. The titlebar color should be dark.
4. Change the theme to light and observe that the titlebar color changes to light.
Version | Supported
------- | ----------
7       | no/only light
8       | no/only light
8.1     | no/only light
Version | Supported
------- | ----------
1607    | no/only light
1809    | yes\*
1909    | yes
2004    | yes
21H1    | yes
21H2    | yes
22H2    | yes
\* 1809: Doesn't update titlebar until activating the window. This behavior is consistent with File Explorer.
Version | Supported
------- | ----------
22H2    | yes

Add support for dark title bar on Windows 10 and later

---

README.md

This isn't meant to be permanent solution but the `docs` repository hasn't been maintained and therefore confuses people.
https://webview.dev currently redirects to this GitHub project.

Remove reference to docs repo

---

webview.h

The existing compile-time condition for calling `webkit_javascript_result_get_js_value()` (WebKitGTK) isn't quite right.
If we consider an imaginary version 3.0, then the condition `WEBKIT_MAJOR_VERSION >= 2 && WEBKIT_MINOR_VERSION >= 22` will evaluate to false because 0 is less than 22. It would however evaluate to true for versions >= 3.22,  >= 4.22, etc.

Fix WebKitGTK >= 2.22 check

---

CHANGELOG.md
MIGRATION.md

This PR splits the migration guide from the changelog and instead adds some release notes into the changelog.
Release notes were not added for old releases because I couldn't find any notes associated with old releases.
After sifting through the PRs since the rewrite, I referenced a few in the changelog that I thought had a major impact on the library compared to the previous release, aside from the major rewrite.
Most of the PRs I picked are coincidentally my own, but the changelog can be amended upon request.

Split migration guide from changelog and add release notes

---

webview.h

The following GCC/Clang compile warnings were fixed/suppressed in the library.
Windows:
* `-Wmissing-braces`
* `-Wtype-limits`
* `-Wcast-function-type` (suppressed)
* `-Wpedantic` (extra ';')
All OS:
* `-Wstrict-prototypes`
The following clang-tidy warnings were fixed/suppressed:
* `bugprone-signed-char-misuse,cert-str34-c`
* `cppcoreguidelines-pro-bounds-constant-array-index`
* `readability-container-contains`
* `modernize-avoid-bind`

Fix various compile/lint warnings

---

webview.h

As it is now, when using webview_return() when WebView is attached to a client window, it doesn't trigger the promize resolve.

The HWND_MESSAGE window is mandatory to have webview_return()  working properly when attaching WebView to a child window.

---

.clang-tidy
webview.h

Building the library on Ubuntu 22.04 emits a warning saying that `webkit_web_view_run_javascript` is deprecated and should be replaced with `webkit_web_view_evaluate_javascript`.
This work adds initial support for dynamically importing `webkit_web_view_evaluate_javascript` while falling back to `webkit_web_view_run_javascript` without issuing a warning. It also facilitates potential future work on deciding at runtime whether to use `webkit2gtk-4.0` or `webkit2gtk-4.1`.
`webkit_web_view_evaluate_javascript` became available in WebKit2GTK 2.40 which is only available for the most recent Linux distros. For example, Ubuntu 20.04 only has WebKit2GTK 2.38 so we can't use `webkit_web_view_evaluate_javascript` there.
What doesn't seem like good options to me:
* Decide at compile-time whether to …

Fix WebKitGTK deprecation warning using modern API with fallback

---

webview.h

Don't attempt to show window or grab focus when a user-owned window is passed in.
Example code:
```c
#include "webview.h"
#include <gtk/gtk.h>
static void activate(GtkApplication *app, gpointer user_data) {
GtkWidget *window = gtk_application_window_new(app);
gtk_window_set_title(GTK_WINDOW(window), "Window");
gtk_window_set_default_size(GTK_WINDOW(window), 480, 320);
webview_t w = webview_create(0, window);
webview_set_html(w, "<input "
"id=\"input\"><script>document.getElementById(\"input\")."
"focus()</script>");
gtk_widget_show_all(window);
*(webview_t *)user_data = w;
}
int main(int argc, char **argv) {
webview_t w = NULL;
GtkApplication *app =
gtk_application_new("org.gtk.example", G_APPLICATION_FLAGS_NONE);
g_signal_connect(app, "activate", G_CALLBACK(activate), &w); …
```

Reduce interference with user-owned window (GTK)

---

webview.h

WebKit 2.42 along with X11 and NVIDIA GPU driver triggers bug: https://bugs.webkit.org/show_bug.cgi?id=261874
The bug causes a blank window. Instead of waiting for the problem to be fixed, this work attempts to check for these conditions before setting the environment variable `WEBKIT_DISABLE_DMABUF_RENDERER` to `1`.
If the variable `WEBKIT_DISABLE_DMABUF_RENDERER` has already been set then the workaround is not applied.
I would have preferred not to implement this workaround but we don't know for how long we'll have to wait for a proper fix or a workaround to land in everyone's favorite Linux distro.
For now we can implement a workaround and then monitor the situation.

Workaround for blank window with WebKit/DMA-BUF/NVIDIA/X11

---

webview.h
webview_test.cc

This work fixes a bug introduced in #1002 where returning UTF-8-encoded strings from bound C++ functions could cause the JS callbacks to not be invoked. The bug could be triggered with characters encoded with a size greater than 1 byte.
Cases of incorrect escaping of characters:
* `DEL` (`0x7f`) isn't required to be escaped and is therefore no longer being escaped.
* `0x80` through `0x9f` were escaped but `0x80` and up is used for multibyte characters in context with UTF-8-encoding. For example, the UTF-8 byte sequence of the Unicode character `⌨` is `0xe3, 0x8c, 0xa8`; however, `0x8c` would be escaped and break the sequence.
* Characters `\b`, `\f`, `\n`, `\r` and `\t` are now properly escaped.
Existing code reserved more memory than needed for the escaped string. This has been …

Fix JSON escaping with UTF-8

---

webview.h

Documentation for this function claimed that it would return an "`HWND` pointer" (pointer to `HWND`?), but it actually returns an `HWND`.
Reworded the documentation for clarity and readability.

Fix webview_get_window documentation for Win32

---

webview.h

The function originally took a pointer to `HWND`, but it's more natural for a caller to pass an `HWND` which by itself is a pointer.
Support for passing a pointer to `HWND` is retained by checking whether the supplied value is an existing window.
Documentation was reworded a bit for clarity.

Allow passing HWND to webview_create (Win32)

---

webview.h

Previously, the webview widget would lose focus when the top-level window went into the background and then into the foreground.
This behavior would break the workflow e.g. during alt-tabbing by requiring the user to click with the mouse inside the webview widget in order to regain focus.
The behavior on Linux is that focus is automatically regained.

Set focus to webview widget when owned window activates (Win32)

---

webview.h

Linux/GTK and macOS/Cocoa both support automatic UI layouting and can therefore automatically resize the webview widget when embedded into a non-owned window, but Windows/Win32 has no automatic layout system. I don't believe that we can non-intrusively determine when the widget should be resized. An intrusive way could be to replace the non-owned window's WndProc.
This work creates a UI widget (child window) that WebView2 can render onto, and this widget is embedded into the top-level window. If we expose the native handle of this widget then we can let the owner of the window take responsibility of resizing the widget.

Embed WebView2 into a child window (Win32)

---

webview.h
webview.i

This is a simple and hopefully harmless change, but allows downstream applications to make deeper platform-specific customizations.
The name `view` was chosen to avoid clash with the class name `webview`.

Expose native handles to web views

---

webview.h

Delete the copy/move constructor/assignment operator of the webview class to make it clear that it doesn't support these operations.
Copying doesn't make much sense here. More work is needed to support `std::move` due to the pointer to the webview class being passed around, e.g. to callback functions. When the original webview instance is moved then callbacks will end up trying to use the original instance, which has become invalid and may have been destroyed already.
Win32 already had the constructors/assignment operators deleted so this simply aligns GTK/Cocoa code with Win32 code.

Delete webview copy/move constructor/assignment

---

webview.h

`native_library` marked move operations as `default` which would copy the handle.
`com_init_wrapper` didn't check itself.

Fix move support in native_library and com_init_wrapper

---

script/build.sh

Fixes a possible error about undefined reference to symbol "dlclose".
Error observed with Ubuntu 20.04.6, GCC 9.4.0.

Link dl library (Linux/macOS)

---

.clang-tidy
examples/bind.c
examples/bind.cc
webview.h
webview_test.cc

* Rename parameter `seq` (sequential number) to `id` (identifier).
* Generate IDs with a length of 32 random characters.
* Replace user (init) script on bind/unbind to fix bug where scripts are never removed and instead pile up for each bind/unbind operation.
* JS RPC operations are now exposed through `window.__webview__`.
A bound function can now be invoked via JS as follows:
window.__webview__.call(name, ...args)
The following is still possible and forwards to `__webview__.call()`:
window.count(...args)
* Modernize examples.
Closes  #731.

Rework RPC code and examples

---

examples/basic.cc
examples/bind.cc
webview.h
webview_test.cc

This is another attempt at improving and facilitating further improvement to error handling and reporting within the library. I already made an attempt with #766 but the approach in this PR is different. #766's primary way of reporting errors was by throwing C++ exceptions. In this PR, the primary way of reporting errors is by returning error information from C++ functions.  The C API returns error codes—same as #766. Exceptions can still be used sparingly such as in constructors.
C/C++ API:
* Add `webview_error_t` enum with error codes.
C++ API:
* Add `error_info` class to hold error information (code, message).
* Add `result` and `noresult` classes for returning to the caller either a success value or error information. `result` should be used for functions that return a value; …

Rework error handling and reporting

---

webview.h
webview_test.cc

It makes sense for `result` to either have a value or an error, but not to have neither.

Default-construct basic_result<T, ...> with value

---

webview.h

Someone may already have it defined on the command line for example.

Avoid warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition

---

script/build.sh

Using the compiler flag `-isystem` instead of `-I` in `build.sh` suppresses warnings coming from `WebView2.h`:
```
D:/a/webview/webview/build/external/libs/Microsoft.Web.WebView2.1.0.1150.38/build/native/include/WebView2.h:19:9: warning: unknown pragma ignored [-Wunknown-pragmas]
19 | #pragma warning( disable: 4049 )  /* more than 64k source lines */
|         ^
```

Suppress warnings from WebView2.h in build.sh

---

examples/basic.c
examples/bind.c

`main()` should be declared as `main(void)` in C.
Fixes the following warnings on macOS:
```
/Users/runner/work/webview/webview/examples/basic.c:16:9: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
int main() {
^
void
1 warning generated.
/Users/runner/work/webview/webview/examples/bind.c:174:9: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
int main() {
^
void
1 warning generated.
```

Fix warnings in C examples

---

webview.h

The `setUIDelegate()` method doesn't increase the `retainCount`, so don't release the delegate.

Do not set an auto released delegate (macOS) (#1113)

---

.github/workflows/ci.yaml
CHANGELOG.md
README.md
script/build.sh
webview.h

Adds support for compiling the webview library with WebKitGTK API 6.0 and GTK 4.
* CI: Builds and tests with WebKitGTK API 4.0, 4.1 and 6.0.
* Readme:
* Updated with more information regarding packages on Linux.
* Updated WebKitGTK API to 4.1 in examples.
* Added information on backend selection with macros.
* Build script now automatically chooses a WebKitGTK API and GTK version, either by the value of the environment variable `WEBKITGTK_API` or from most modern API to least modern API (6.0, 4.1, 4.0).
* Since `gtk_main()` and `gtk_main_quit()` were removed from GTK 4, `webview::terminate()` now sets a flag that will cause `webview::run()` to return.
Since `webkit_web_view_run_javascript()` became deprecated in WebKitGTK 2.40, compiler warnings were issued until we decided to dynamically …

Add support for WebKitGTK API 6.0 and GTK 4

---

README.md

* Link referred to GTK 3 only.
* Fedora used package for GTK3 instead of GTK4.

Fix GTK info in readme

---

README.md

The remaining information in this section regarded macOS app bundles, and keeping it wouldn't be as useful anymore because the code examples now include app bundles with icons.

Remove info on app distribution from readme

---

cmake/internal.cmake
core/CMakeLists.txt

Sets the `cxx_std_11` compile feature on the `webview_core_headers` CMake target so that the minimum C++ standard used by targets that link it is C++11. This can be overridden by the `CMAKE_CXX_STANDARD` variable.

Use cxx_std_11 compile feature

---

.clang-format
core/include/webview/webview.h

clang-format-16 and later (18) do not agree with clang-format-15 and earlier (9) on how to format the member initializers in the constructor of cocoa_wkwebview_engine.
By enabling ConstructorInitializerAllOnOneLineOrOnePerLine, the initializers are formatted consistently either on a single line or on separate lines if they can't fit on a single line.
This option was introduced in clang-format 3.7 and is currently deprecated. The replacement appears to be PackConstructorInitializers, which was introduced in clang-format-14. The deprecated option is used here to retain the same clang-format (9) compatibility.

Fix clang-format conflict before and after v16

---

core/include/webview/webview.h

This PR addresses linker issues similar to those found in issue #378 , by adding inline to `get_file_version_string` and `cast_to_webview`
I am able to get this project to build an run sucessfully if all of the webview code is contained in a single source file `main.cc` but if I split the code and use multiple source files, it introduces linker errors similar to issue #378.
here is key info from my build output so you can see the environment/compiler/build tools etc. 
```bash
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The CXX compiler identification is MSVC 19.40.33813.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe …
```

added inline to get_file_version_string and cast_to_webview

---

core/include/webview/detail/backends/cocoa_webkit.hh
core/include/webview/detail/platform/darwin/cocoa.hh

Docking the Web Inspector (Developer Tools) pane to the bottom of the main window resulted in portions of the the web view to be pushed out of bounds. The pane would also flicker when docked to the right side.
The cause of the issue appears to be that when the Web Inspector is opened, it's automatically added into the view hierarchy as a sibling of the web view, but the web view was set as the window's content view.
In order to make the web view and Web Inspector more self-contained, a new widget is now containing both, with proper auto-resizing.

Fix Web Inspector layout (macOS)

---

core/include/webview/detail/backends/cocoa_webkit.hh
core/include/webview/detail/engine_base.hh

These changes allow an app built with the webview library to run on older versions of macOS.
Tested with the following versions of the operating system:
* OS X El Capitan 10.11
* macOS High Sierra 10.13
* macOS Sequoia 15

Runtime compatibility with old macOS

---

.github/workflows/ci.yaml
README.md
scripts/amalgamate.py

The amalgamation script fails on Windows due to file locking/sharing issues.
This work creates a temporary directory instead without keeping any temporary files open.
A CI job was also added for testing the amalgamation script with different versions of Python on different platforms so that this type of issue will be caught sooner.
The minimum Python version required by this script is 3.9 because of the `graphlib` module used.

Fix amalgamation script failing on Windows

---

core/include/webview/detail/backends/cocoa_webkit.hh
core/include/webview/detail/backends/gtk_webkitgtk.hh
core/include/webview/detail/backends/win32_edge.hh
core/include/webview/detail/user_script.hh

When compiling in C++23 mode using Clang, compilation failed in `~unique_ptr()` due to user_script::impl being an incomplete type.
Issue was observed with Clang 16 and 18 on Linux/macOS, with C++23 set via `CMAKE_CXX_STANDARD`. C++20 and earlier did not yield an error.
The issue could not be observed with GCC 13.2 and 14.2 on Linux.
Fixes #1215

Fix deletion of incomplete type user_script::impl

---

core/include/webview/detail/backends/gtk_webkitgtk.hh

Prior to this PR, the function continues to execute the error return after the if-statements, causing the error to always trigger.

gtk: fix error unconditionally triggering for webview_set_size

---

webview.i

The type definition in 'api.h' for the 'hints' parameter of `webview_set_size` is `webview_hint_t`, but this is defined as `int` in the SWIG interface. This discrepancy causes compilation warnings and errors.

Corrects the `hints` parameter type for `webview_set_size`

---

core/include/webview/detail/backends/cocoa_webkit.hh
core/include/webview/detail/backends/gtk_webkitgtk.hh
core/include/webview/detail/backends/win32_edge.hh
core/include/webview/detail/platform/darwin/cocoa.hh
core/include/webview/detail/platform/darwin/objc.hh
core/include/webview/detail/platform/darwin/webkit.hh
core/include/webview/detail/platform/linux/gtk/compat.hh
core/include/webview/detail/platform/linux/webkitgtk/compat.hh
core/include/webview/detail/platform/linux/webkitgtk/dmabuf.hh
core/include/webview/detail/platform/windows/com_init_wrapper.hh
core/include/webview/detail/platform/windows/dpi.hh
core/include/webview/detail/platform/windows/dwmapi.hh
core/include/webview/detail/platform/windows/iid.hh
core/include/webview/detail/platform/windows/ntdll.hh
core/include/webview/detail/platform/windows/reg_key.hh
core/include/webview/detail/platform/windows/shcore.hh
core/include/webview/detail/platform/windows/theme.hh
core/include/webview/detail/platform/windows/user32.hh
core/include/webview/detail/platform/windows/version.hh
core/include/webview/detail/platform/windows/webview2/loader.hh

Re-enables code syntax highlighting in code editors for files that enable code based on whether platform/backend-specific macros are defined.
Example:
#if defined(WEBVIEW_PLATFORM_LINUX) && defined(WEBVIEW_GTK)
#endif
Without the `macros.h` header, `WEBVIEW_PLATFORM_LINUX` and `WEBVIEW_GTK` would by default appear to be undefined in code editors.

Include macros.h

---

.github/actions/cmake/action.yaml
core/tests/src/tests.cc

Sets a 60 second timeout for tests. There used to be a timeout in the past but after the switch to CMake/CTest and the test driver rewrite, no timeout had been set.
Dummy tests that sleep the thread show that the timeout works (10s here but later changed to 60s):
```
Start  6: Temporary test to ensure that timeout works (10s)
6/17 Test  #6: Temporary test to ensure that timeout works (10s) .........***Timeout  10.01 sec
Start  7: Temporary test to ensure that timeout works (11s)
7/17 Test  #7: Temporary test to ensure that timeout works (11s) .........***Timeout  10.01 sec
Start  8: Temporary test to ensure that timeout works (9s)
8/17 Test  #8: Temporary test to ensure that timeout works (9s) ..........   Passed    9.03 sec
```

CI test timeout

---

README.md

Implement Vala binding, but yet support embed webview as a GTK4 widget, I need help.
@SteffenL Is something I missed?

Add Vala binding

---

.github/workflows/build_matrix.csv

The ubuntu-20.04 image is scheduled for removal and this change is to avoid disruption.
https://github.com/actions/runner-images/issues/11101

Update Ubuntu GHA runner image from 20.04 to 22.04

---

README.md
cmake/modules/FindMSWebView2.cmake
core/include/webview/detail/platform/windows/com_init_wrapper.hh
core/include/webview/detail/platform/windows/dpi.hh
core/include/webview/detail/platform/windows/version.hh
core/include/webview/detail/platform/windows/webview2/loader.hh

This work makes some changes that are necessary for lowering the minimum required C++ standard on Windows from C++14 to C++11.
I can't recall why `cxx_std_14` was set instead of `cxx_std_11` for the `MSWebView2::headers` CMake target but it may have been under the wrong belief that it wouldn't work with `cxx_std_11`. Now it does appear to work with the MinGW distributions we test with so making this change seems reasonable to me.
Some code for Windows were using C++14 features and have been replaced to be compatible with C++11.
While at it, the move constructor and assignment operator of `com_init_wrapper` should have been marked with `noexcept` and has therefore been marked as such.

C++11 compatibility for Windows

---

core/include/webview/detail/backends/win32_edge.hh

This PR:
- Fixes a visual issue where the default size was set before the user size, causing a rendering glitch
- Refactors win32_edge to a more standardised backend code flow

Fix window rendering glitch and refactor win32 edge

---

core/include/webview/detail/platform/darwin/objc/memory.hh

Corrects the return type used with `msg_send()` in `objc::release()`. This correction has no impact on behavior.

Use void return type internally in objc::release()

---

core/include/webview/detail/backends/win32_edge.hh

For Windows WebView2 engine
This patch will add 200ms delay before retry `try_create_environment` and up to 12s
This is for a very edge case but I have encountered, the controller will fail creating.
To reproduce that situation:
1. create a clear and WebView2 installed Windows image (i.e. vm image)
2. set a schedule task to open the webview based app when user logging in
3. it will work fine at this time
4. burn the image into any disk then install it into any other machine (whatever it's vm or real machine)
5. when the system bootup, there must be "prepare devices" hint and display reinstall (short scale animation) otherwise this may not occur 
6. `CreateCoreWebView2Contoller` will fail with `0x80070490 ERROR_NOT_FOUND` and 5 retires do nothing
Maybe there's better way to fix it, but …

Sleep before retry try_create_environment for WebView2

---

core/include/webview/detail/backends/cocoa_webkit.hh
core/include/webview/detail/backends/gtk_webkitgtk.hh
core/include/webview/detail/backends/win32_edge.hh
core/include/webview/detail/engine_base.hh

Passing a flag in the constructor of `engine_base` is less error-prone.

Remove set_owns_window()
