webview.h
=> center by default on windows

webview.h
Please refer https://github.com/zserge/webview/issues/8#issuecomment-350035663
=> webview: rename the "weird" invoke_ to invoke

webview.h
This fixes a bug where JavaScript is disabled in the application if the user has increased their security level in IE.
Hi, let me know if there are formatting issues, I do not usually do C programming.
=> Add IInternetSecurityManager to override any IE settings.

webview.go
Fixes https://github.com/zserge/webview/issues/297
=> FIx build on Mac OS X Catalina / XCode 11

README.md
Ubuntu Quick Pointer to help newbs. By the way, I'm sorry Edge got moved to Chromium, please let us know what you are going to do to this neat project otherwise.
=> Ubuntu Quick Pointer

README.md
I tried to compile with cl.exe and was successful.  Just want to put it in for others who may want to do the same.
=> Add doc on how to compile with Microsoft cl.exe

webview.h
add the line
`#define WEBVIEW_SUPRESS_ERRORS`
to supress the nasty warnings/error notifications/messageboxes from the IE
=> Add option to supress warnings for IE

webview.go
Augment package godoc by copying function comments from C source to Go
code and making minor edits.
Current godoc shows a [useful interface](https://godoc.org/github.com/zserge/webview#WebView), but no
documentation on how to use its methods. I discovered the C code was
well documented, and copied function documentation over, adapting it
to the Go idiom of beginning each function comment with the name of the
function (see [the Go Blog](https://blog.golang.org/godoc-documenting-go-code)).
After changes:
```
$ go doc -all .
package webview // import "github.com/zserge/webview"
CONSTANTS
const (
// Width and height are default size
HintNone = C.WEBVIEW_HINT_NONE
// Window size can not be changed by a user
HintFixed = C.WEBVIEW_HINT_FIXED
// Width and height are minimum bounds
HintMin = …
```
=> Add function and method comments to Go code

webview.go
Provides support for binding variadic Go functions.
=> Handle binding of variadic functions (Go)

webview.h
Previously the code passed a nullptr to the creation of the Edge/Chromium Webview. This defaults the webview to create a user data folder in the folder of the calling executable. In case of an installed application, the executing user may not have the permissions to do this. This commit changes the default user data folder to "%APPDATA%/[EXECUTABLE_NAME]". Fixes #362
=> Change Edge/Chromium user data folder

README.md
C is supported, but has no examples or documentation for the user.
This is an example me and @justjosias put together by looking
through the source code.
=> Add C example and build instructions

go.mod
=> Updated go.mod to point to this repo

README.md
an addition to [this](https://github.com/webview/webview/pull/429)
=> update readme to point to right repo

webview.h
Fixes #515 - enable browser contro…lled fullscreen in MacOS
=> Enable browser controlled fullscreen in MacOS

go.mod, webview.h
=> Fixed url_decode function

README.md
Not sure about the gitter ones, but the Godoc etc seem like a good change
=> Use present repository name throughout README

webview.go, webview.h
=> Fix MIME type in documentation

main.cc
Adding V0G0N raw string literals (C++11) for better HTML/CSS/JS code source string processing.
=> Adding V0G0N raw string literals (C++11)

README.md
Updated C example repo to webview_c to be more consistent
=> Update C example yet again

webview.h
Double-checked on windows this morning and had to change 2 lines to get it to work. Also removed unnecessary line.
=> Fix set-html on Windows

README.md, examples/scrape/main.go
not sure if this belongs in README but thought someone else might need this
=> Add web scraping example

webview_test.cc
Avoids some unnecessary copies.
=> Use reference to const auto

webview.h
=> Bind functions immediately rather than waiting for next load

webview.h
=> Navigate to about:blank rather than predefined blank page

README.md
Just a few minor fixes and rewordings.
=> README rewordings and documentation fixes

main.c
This file is not currently being formatted by build scripts.
This can either be merged immediately while considering #763, or the file could be added to be formatted in the current build scripts. Due to #763 changing the same build scripts I'm delaying work on the build scripts here.
=> Call webview_set_html in C example and fix formatting

LICENSE, webview.h
Since I have dedicated a considerable amount of time and effort for this project for a while now and expect to continue doing so, I would like to put my name somewhere more visible. In this PR I have therefore added myself to the copyright notices.
Thank you for your consideration.
=> Add myself to copyright notice

webview.h
See commit messages.
Fixes issues raised in #781.
=> Fix window icon on Windows

webview.h
Please see the commit messages for the reasons behind these changes.
Tested on macOS  12.4.
=> Fix macOS app termination

README.md
=> Add Deno bindings to readme

README.md
Added V language support url to the README file
=> README: Added V language support

webview_test.cc
Adds some simple tests for async/sync bind/unbind.
=> Add tests for bind/unbind

webview.h
Removes usage of new/delete in bind/unbind for simpler and safer C++ code.
=> Refactor C++ binding implementation

README.md
Updates readme based on feedback by @steowens in #879.
=> Clarify instructions in readme

script/build.sh
* Allow specifying target architecture for Go.
* Allow overriding `pkg-config` executable.
* Specify `-m<32|64>` flag when cross-compiling.
Cross-compile library to x86 on Linux (Ubuntu):
```sh
PKGCONFIG=i686-linux-gnu-pkg-config TARGET_ARCH=x86 ./script/build.sh
```
Make sure to install packages: `libgtk-3-dev:i386`, `libwebkit2gtk-4.0-dev:i386`
```sh
$ readelf --file-header build/library/libwebview.so | grep Class:
Class:                             ELF32
$ readelf --file-header build/examples/cc/basic | grep Class:
Class:                             ELF32
$ readelf --file-header build/examples/go/basic | grep Class:
Class:                             ELF32
```
=> Cross-compilation improvements

README.md
As the title says, this PR adds my swift bindings to the bindings table in the README
=> Adds swift bindings to table

README.md
=> Add binding for Bun JS runtime to readme

README.md
=> Add binding for Harbour to readme

CHANGELOG.md, webview.h
=> Disable status bar (Windows/WebView2)

webview.h
Only show window and grab focus when window is owned.
Also update the documentation of `webview_create` to make it more clear that responsibilities change depending on whether an existing window is passed in.
=> Reduce interference with user-owned window (Win32)

webview.h
Calling `terminate()` can cause unintended behavior when using multiple `webview` instances in the same application.
```cpp
#include "webview.h"
constexpr const auto html =
R"html(<button id="quitButton">Quit</button>
<script>
(() => {
const quitButton = document.getElementById("quitButton");
quitButton.addEventListener("click", () => {
window.quit();
});
})();
</script>)html";
int main() {
{
webview::webview w(false, nullptr);
w.set_title("Window 1");
w.set_size(480, 320, WEBVIEW_HINT_NONE);
w.bind("quit", [&](const std::string & /*req*/) -> std::string {
w.terminate();
return "";
});
w.set_html(html);
w.run();
}
{
webview::webview w(false, nullptr);
w.set_title("Window 2");
w.set_size(480, 320, WEBVIEW_HINT_NONE);
w.set_html("Another window");
w.run();
}
return 0;
}
```
1. After …
=> Prevent unintentionally posting quit message multiple times (Win32)

webview.h
Each backend implemented methods that were part of the C++ API; however, the compiler didn't enforce this. This work moves code from the `webview` class into a new `browser_engine_base` class that each backend should inherit rather than being a base class of the `webview` class. Pure virtual methods in the  ase class ensure that each backend must implement the methods.
Another benefit is that each backend can share common code through the base class.
For now, the "webview" type is an alias of "browser_engine" in order to retain backward compatibility.
This change also eliminates some code that had been duplicated into the backend classes.
=> Change webview class hierarchy

webview.h
We used to let the system/UI framework automatically handle when to terminate the app after the last window was closed. We used custom logic to stop the run loop instead of terminating the whole process.
Now we handle the stopping of the run loop without having to awkwardly initiate termination just to block it and do something else instead.
Future work can e.g. add a flag that allows the user of the library to choose whether to "terminate" (stop the run loop) when the last window is closed.
=> Last window closed custom logic (macOS)

webview.h
See commit messages for details. Fixes various issues related to behavior and cleanup upon destruction of webview instances.
=> Fixes for destruct behavior/cleanup

webview.h
Adds more autorelease pools and adds certain objects to autorelease pools that otherwise would have leaked memory.
There still appears to be some memory-related issues though. For example, `m_manager`, which is retrieved from `WKWebViewConfiguration`'s `userContentController` property, still lingers at the end of `~cocoa_wkwebview_engine`.
Just to be clear: If we wrap the pool into a scope and check `m_manager` outside the scope (so the pool is drained), `m_manager` is still alive at that point.
We can check whether it's still alive by sending the `retainCount` message and checking the value. If there's a crash then the object is gone already; otherwise, we get a value greater than 0.
=> Fix various memory management issues (macOS)

README.md
This PR fix error in readme.md for the cmake Git_Tag
=> Fix error in readme.md for the cmake Git_Tag

.clang-tidy, README.md, core/tests/src/tests.cc, examples/basic.cc, examples/bind.cc, test_driver/include/webview/test_driver.hh
Fixes and suppresses new issues observed when using Clang Tidy 18.
=> Fix/Suppress Clang Tidy 18 issues

core/include/webview/detail/backends/cocoa_webkit.hh, core/include/webview/detail/backends/gtk_webkitgtk.hh, core/include/webview/detail/backends/win32_edge.hh, core/include/webview/detail/engine_base.hh
Avoids some excess dispatching on Windows while organizing code better.
=> Temporary run loop refactor

core/include/webview/detail/backends/cocoa_webkit.hh
Adds global `m_app` which is initiated in the class constructor to reduce multiple calls to `app = get_shared_application()`
=> Refactor cocoa_webkit for DRY get_shared_application

core/include/webview/detail/engine_base.hh
Adds methods and members to engine base that enable addressing issues and refactoring from #1249
=> Enable backend refactoring
